name: budget_master
description: Global Budget System PRO
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1

flutter:
  uses-material-design: true
